name: Release build

on:
  push:
    tags:
      - "v*"
    #branches:
    #  - release/**

jobs:
  linux:
    name: Build Binary on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust stable toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Run cargo build
        run: cargo build --bins --release --locked

      - name: Split and archive debug info
        run: |
          mkdir -p build

          # Split only symbolicator's debug information
          objcopy --only-keep-debug target/release/symbolicator{,.debug}
          objcopy --strip-debug --strip-unneeded target/release/symbolicator
          objcopy --add-gnu-debuglink target/release/symbolicator{.debug,}
          zip -j build/symbolicator-Linux-x86_64-debug.zip target/release/symbolicator.debug

          # Strip debug info for tools
          objcopy --strip-debug --strip-unneeded target/release/wasm-split
          objcopy --strip-debug --strip-unneeded target/release/symsorter
          objcopy --strip-debug --strip-unneeded target/release/symbolicli

          # Move all binaries
          mv target/release/symbolicator build/symbolicator-Linux-x86_64
          mv target/release/wasm-split build/wasm-split-Linux-x86_64
          mv target/release/symsorter build/symsorter-Linux-x86_64
          mv target/release/symbolicli build/symbolicli-Linux-x86_64

      # - uses: actions/upload-artifact@v3.1.1
      #   with:
      #     name: ${{ github.sha }}
      #     path: build/*

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/branches/release/')
        with:
          # tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            build/symbolicator-Linux-x86_64
            build/wasm-split-Linux-x86_64
            build/symsorter-Linux-x86_64
            build/symbolicli-Linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
      # - name: Upload Release Assets
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
      #   run: |
      #     gh release upload ${{ github.ref }} ./build/*
