name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (optional)
        required: false
      force:
        description: Force a release even when there are release-blockers (optional)
        required: false
  schedule:
    # We want the release to be at 9-10am Pacific Time
    # We also want it to be 1 hour before the on-prem release
    - cron: "0 17 15 * *" # 5pm UTC on the 15th of every month
jobs:
  release:
    runs-on: ubuntu-latest
    name: "Release a new Symbolicator version"

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_RELEASE_PAT }}
          fetch-depth: 0
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        run: |
          gh release upload ${{ github.ref }} ./build/*

      # - name: Prepare release
      #   uses: getsentry/action-prepare-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
      #   with:
      #     version: ${{ github.event.inputs.version }}
      #     force: ${{ github.event.inputs.force }}
      #     calver: true
